agent_name: sac

env:
  id: CarRacing-v3
  num_stack: 3

training:
  episodes: 100
  max_steps_per_episode: 300
  warmup_steps: 2000
  train_every: 1
  updates_per_step: 1   # ok for debug

hyperparameters:
  replay_size: 30000
  batch_size: 32
  gamma: 0.99
  lr: 0.0003
  automatic_entropy_tuning: false
  actor_lr: 0.0001
  critic_lr: 0.0003
  alpha: 0.01

network:
  cnn_channels: [32, 64, 64]
  fc_sizes: [256, 128]

output:
  checkpoint_dir: checkpoints/sac_debug
